# KFold Cross Validation

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits=load_digits()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

# Logistic Regression

In [16]:
lr = LogisticRegression(solver='liblinear')
lr.fit(X_train,y_train)

LogisticRegression(solver='liblinear')

In [17]:
lr.score(X_test,y_test)

0.9666666666666667

# SVM

In [19]:
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)

SVC(gamma='auto')

In [20]:
svm.score(X_test,y_test)

0.3055555555555556

# Random Forest

In [25]:
rf=RandomForestClassifier(n_estimators=20)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=20)

rf.score(X_test,y_test)

#  Basic example

In [28]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [29]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Use KFold for our digits example

In [30]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [34]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [33]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [35]:
scores_svm


[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [36]:
scores_rf

[0.9315525876460768, 0.9465776293823038, 0.9282136894824707]

# cross_val_score function

In [37]:
from sklearn.model_selection import cross_val_score

# Logistic regression model performance using cross_val_score

In [39]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

# svm model performance using cross_val_score

In [40]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

# random forest performance using cross_val_score

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92988314, 0.94323873, 0.93322204])

# Parameter tunning using k fold cross validation

In [42]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)


np.float64(0.882042209807573)

In [43]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

np.float64(0.9448944754810675)

In [46]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

np.float64(0.9521415270018622)