In [1]:
! pip install numpy

### IMPORT LIBRARIES

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4])

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4]


In [4]:
%%time

lst = list(range(1000000))

for i in range(1000000):
    lst[i] *= lst[i]

CPU times: total: 266 ms
Wall time: 265 ms


In [5]:
%%time

arr = np.arange(1000000)

arr = arr * arr


CPU times: total: 15.6 ms
Wall time: 5.18 ms


In [6]:
# Creating a simple array in numpy

arr = np.array([1, 2, 3, 4])

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4]


In [7]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [8]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [10]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [11]:


arr = np.array(43)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 43
Shape:  ()
Data Type:  int64
Item Size:  8
Dimensionality:  0


In [12]:
arr = np.array([1, 2, 3, 4])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4]
Shape:  (4,)
Data Type:  int64
Item Size:  8
Dimensionality:  1


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Data Type:  int64
Item Size:  8
Dimensionality:  2


In [14]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape:  (2, 2, 3)
Data Type:  int64
Item Size:  8
Dimensionality:  3


In [15]:
arr = np.ones((3, 3))

print("Array: \n", arr)

Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arr = np.zeros((3, 3))

print("Array: \n", arr)


Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr = np.eye(3)

print("Array: \n", arr)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
arr = np.array([2, 1, 4, 5], dtype='float16')
arr

array([2., 1., 4., 5.], dtype=float16)

In [6]:
arr = np.array([2, 1, 4, 5], dtype='object')
arr

array([2, 1, 4, 5], dtype=object)

In [9]:
arr = np.array(["Hi", "Hello"], dtype='S10')
arr

array([b'Hi', b'Hello'], dtype='|S10')

In [10]:
arr = np.array(["Hi", "Hello"], dtype='S20')
arr

array([b'Hi', b'Hello'], dtype='|S20')

In [12]:
arr = np.array(["Hi", "Hello", "Hello World"], dtype='U5')
arr

array(['Hi', 'Hello', 'Hello'], dtype='<U5')

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Numpy Random Numbers**

1. **np.random.rand** - generates an array with random numbers that are uniformly distribute between 0 and 1.
2. **np.random.randn** - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
3. **np.random.randint** - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
4. **np.random.uniform** - generates an array with random numbers (float) between given numbers.

In [19]:
# Randomly generate an array from uniform distribution
arr = np.random.rand(5)
arr

array([0.73748593, 0.33423461, 0.589872  , 0.22368768, 0.33781503])

In [20]:
# Randomly generate an array with 10 rows and 2 columns
arr = np.random.rand(10, 2)
arr

array([[0.22756256, 0.52940861],
       [0.36988287, 0.94873074],
       [0.64591586, 0.03248067],
       [0.09873934, 0.58390201],
       [0.55007597, 0.83900857],
       [0.07616388, 0.94524919],
       [0.33406558, 0.7468259 ],
       [0.76610971, 0.68647444],
       [0.10915844, 0.63237196],
       [0.99916084, 0.5170953 ]])

In [21]:
# Randomly generate an array from normal distribution
arr = np.random.randn(5)
arr

array([-0.19348568,  0.405738  ,  0.22840705, -0.56458262,  0.50580326])

In [23]:
# Randomly generate an array with 5 rows and 4 columns4
arr = np.random.randn(5, 4)
arr

array([[-0.92739487,  1.48483466, -1.3396921 , -0.86188734],
       [ 0.90315187, -1.98498885, -0.55227807,  0.41199768],
       [-0.07070989, -0.22343548, -0.336405  , -1.39670714],
       [-0.94363756, -0.29580388, -1.60599819, -0.23078882],
       [-0.31483783,  0.11530893, -0.75861785, -0.44822601]])

In [24]:
# Generate one random integer between 0 to 9

value = np.random.randint(10)

print(value)

2


In [25]:
# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[3 5 2 3]
 [7 0 8 9]
 [6 9 7 8]
 [1 7 4 7]
 [6 5 0 2]]


In [26]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[39 10 14 34 15 24 10 38 33 26]
 [31 10 11 25 38 20 12 34 15 25]
 [35 32 27 33 17 21 21 22 39 19]
 [22 26 37 38 30 34 27 25 22 21]
 [32 34 34 18 34 14 25 19 25 18]]


In [27]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)

print(value)

4.390702635278153


In [28]:
# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[2.49979064 7.20437389 1.69157263 2.2843305 ]
 [8.33258004 3.70844148 4.62652601 9.64086323]
 [8.0374574  9.05033462 7.3447642  7.46018914]
 [2.13353619 5.38706369 3.3430429  8.90532471]
 [2.08577805 2.94796005 3.6044124  3.79753071]]


In [29]:
# Randomly generate a 5*3 array containing values in the range of 10 to 40
arr = np.random.uniform(10, 40, size = (5, 3))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[21.77505522 19.34623759 12.09487222]
 [22.97609206 30.81873773 26.79888811]
 [18.94843477 32.13673532 21.73960957]
 [30.02492153 34.95012907 21.952774  ]
 [12.93134554 12.03691176 26.14272541]]


In [30]:
arr = np.random.randint(100, size = (5, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [58 45 66 74 19]
Shape:  (5,)


In [32]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  66


In [33]:
# Accessing 5th index
print("Value at 5th index: ", arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [34]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[28 81 37 40]
 [ 8 23 70 14]
 [60 23  8 65]
 [42 33 66 79]
 [69 73 75 46]]


In [35]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  [60 23  8 65]


In [36]:
# Accessing value at 2, 1 index
print("Accessing Value using Way-1: ", arr[2][1])

print("Accessing Value using Way-2: ", arr[2, 1]) 
# Way-2 syntax can be helpful to access multiple values

Accessing Value using Way-1:  23
Accessing Value using Way-2:  23


In [37]:
# Accesssing multiple values
print(arr[[2, 1], [1, 1]])

[23 23]


In [38]:
arr = np.random.randint(100, size = (10, ))

In [39]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[63 59 87 48]


In [40]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Create a boolean mask

print(mask)

[False False  True  True  True]


In [41]:
filtered_arr = arr[mask]  # Apply mask

print(filtered_arr)

[30 40 50]


In [42]:
arr = np.array([5, 10, 15, 20, 25, 30])

mask = (arr > 10) & (arr < 25)  # Select numbers between 10 and 25

print(arr[mask])

[15 20]


In [43]:
arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [49 73 66 80 87 70 62 89 48 92]
Shape:  (10,)


In [44]:
arr_slice = arr[1:4]

print("Array Slice Before:", arr_slice)

# Updating the arr_slice element at index 1
arr_slice[1] = 99999

print("Array Slice After:", arr_slice)
print()
print("Original Array:", arr)

Array Slice Before: [73 66 80]
Array Slice After: [   73 99999    80]

Original Array: [   49    73 99999    80    87    70    62    89    48    92]


### **How to tell if the array is a view or a copy?**

The **base** attribute of the ndarray makes it easy to tell if an array is a view or a copy. The base attribute of a view returns the original array while it returns None for a copy.

In [45]:
print(arr.base) # base attribute of copy returns None

print(arr_slice.base) # base attribute of view returns the original arra

None
[   49    73 99999    80    87    70    62    89    48    92]


In [46]:
print(arr[1:4])

[   73 99999    80]


In [47]:
print(arr[0:-4])

[   49    73 99999    80    87    70]


In [48]:
print(arr[::2])

[   49 99999    87    62    48]


In [49]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape:  (3, 4)


In [50]:
print(arr[:2, 1:3])

[[2 3]
 [6 7]]


In [51]:
print(arr[1:2, :])

[[5 6 7 8]]


In [52]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

# Update a single element
arr[1, 1] = 9999

print("Updated Array: \n", arr)

Original Array: 
 [[12 45 79 17]
 [70 27 25 68]
 [49 88 11 61]
 [91 51 75  6]
 [41 65 97 39]]
Updated Array: 
 [[  12   45   79   17]
 [  70 9999   25   68]
 [  49   88   11   61]
 [  91   51   75    6]
 [  41   65   97   39]]


In [53]:
arr[[0, 4], [0, 1]] = [8888, 7777]

print("Updated Array: \n", arr)

Updated Array: 
 [[8888   45   79   17]
 [  70 9999   25   68]
 [  49   88   11   61]
 [  91   51   75    6]
 [  41 7777   97   39]]


In [54]:
arr[0] = [100, 200, 300, 400]

print("After updating row 0:\n", arr)

After updating row 0:
 [[ 100  200  300  400]
 [  70 9999   25   68]
 [  49   88   11   61]
 [  91   51   75    6]
 [  41 7777   97   39]]


In [55]:
arr = np.array([10, 20, 30, 40])

print("Original Array:\n", arr)

Original Array:
 [10 20 30 40]


In [56]:
new_arr = np.insert(arr, 2, 25)  # Insert 25 at index 2

print("After Insertion:", new_arr)

After Insertion: [10 20 25 30 40]


In [57]:
new_arr = np.insert(arr, [1, 3], [99, 88])

print("Original Array:\n", arr)
print()
print("After Insertion:", new_arr)

Original Array:
 [10 20 30 40]

After Insertion: [10 99 20 30 88 40]


In [58]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[20 39 37 22 22 26 16 18 26 38]
 [34 23 14 17 20 29 29 19 21 15]
 [29 30 20 33 16 28 37 36 38 26]
 [24 10 29 19 16 11 13 17 31 14]
 [11 12 21 12 30 10 24 20 19 37]]
Shape:  (5, 10)


In [59]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [20 39 37 22 22 26 16 18 26 38 34 23 14 17 20 29 29 19 21 15 29 30 20 33
 16 28 37 36 38 26 24 10 29 19 16 11 13 17 31 14 11 12 21 12 30 10 24 20
 19 37]
Shape:  (50,)


In [60]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [20 39 37 22 22 26 16 18 26 38 34 23 14 17 20 29 29 19 21 15 29 30 20 33
 16 28 37 36 38 26 24 10 29 19 16 11 13 17 31 14 11 12 21 12 30 10 24 20
 19 37]
Shape:  (50,)


In [61]:
# Updating value in the array
print("Original Array: \n", arr)

Original Array: 
 [[20 39 37 22 22 26 16 18 26 38]
 [34 23 14 17 20 29 29 19 21 15]
 [29 30 20 33 16 28 37 36 38 26]
 [24 10 29 19 16 11 13 17 31 14]
 [11 12 21 12 30 10 24 20 19 37]]


In [62]:
flatten_arr[1] = 99

print("Flatten Array: \n", flatten_arr)

print("Original Array: \n", arr)

Flatten Array: 
 [20 99 37 22 22 26 16 18 26 38 34 23 14 17 20 29 29 19 21 15 29 30 20 33
 16 28 37 36 38 26 24 10 29 19 16 11 13 17 31 14 11 12 21 12 30 10 24 20
 19 37]
Original Array: 
 [[20 39 37 22 22 26 16 18 26 38]
 [34 23 14 17 20 29 29 19 21 15]
 [29 30 20 33 16 28 37 36 38 26]
 [24 10 29 19 16 11 13 17 31 14]
 [11 12 21 12 30 10 24 20 19 37]]


In [63]:
ravel_arr[1] = 99

print("Ravel Array: \n", ravel_arr)

print("Original Array: \n", arr)

Ravel Array: 
 [20 99 37 22 22 26 16 18 26 38 34 23 14 17 20 29 29 19 21 15 29 30 20 33
 16 28 37 36 38 26 24 10 29 19 16 11 13 17 31 14 11 12 21 12 30 10 24 20
 19 37]
Original Array: 
 [[20 99 37 22 22 26 16 18 26 38]
 [34 23 14 17 20 29 29 19 21 15]
 [29 30 20 33 16 28 37 36 38 26]
 [24 10 29 19 16 11 13 17 31 14]
 [11 12 21 12 30 10 24 20 19 37]]


In [64]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[38 25 15 20 12 23 25 31 35 33]
 [38 28 31 26 13 37 14 28 32 35]
 [10 12 32 30 37 28 26 37 18 19]
 [26 38 13 29 17 23 25 18 28 24]
 [15 39 28 36 23 15 32 26 18 25]]
Shape:  (5, 10)


In [65]:
arr_reshaped = arr.reshape(10, 5)

print(arr_reshaped)

[[38 25 15 20 12]
 [23 25 31 35 33]
 [38 28 31 26 13]
 [37 14 28 32 35]
 [10 12 32 30 37]
 [28 26 37 18 19]
 [26 38 13 29 17]
 [23 25 18 28 24]
 [15 39 28 36 23]
 [15 32 26 18 25]]


In [66]:
arr_reshaped = arr.reshape(25, 2)

print(arr_reshaped)

[[38 25]
 [15 20]
 [12 23]
 [25 31]
 [35 33]
 [38 28]
 [31 26]
 [13 37]
 [14 28]
 [32 35]
 [10 12]
 [32 30]
 [37 28]
 [26 37]
 [18 19]
 [26 38]
 [13 29]
 [17 23]
 [25 18]
 [28 24]
 [15 39]
 [28 36]
 [23 15]
 [32 26]
 [18 25]]


In [67]:
# arr_reshaped = arr.reshape(3, 3)

# print(arr_reshaped)

In [68]:
# arr_reshaped = arr.reshape(5, 50)

# print(arr_reshaped)

In [69]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


In [70]:
# Randomly generate an array containing values in the range of 10 to 39
import numpy as np

arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [36 20 14 34 31 12 10 12 18 20]
Shape:  (10,)


In [71]:
# Looping over items in the array
for item in arr1d:
    print(item, end=" ")

36 20 14 34 31 12 10 12 18 20 

In [72]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr2d = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr2d)

print("Shape: ", arr2d.shape)

Numpy Array: 
 [[12 14 28 36 33 23 38 11 12 25]
 [30 34 25 37 17 37 10 33 39 24]
 [31 22 36 14 13 38 38 35 11 16]
 [14 15 17 34 15 12 15 38 10 17]
 [39 15 19 27 28 13 31 14 32 12]]
Shape:  (5, 10)


In [73]:
# Looping over rows in the 2d array
for row in arr2d:
    print(row)

[12 14 28 36 33 23 38 11 12 25]
[30 34 25 37 17 37 10 33 39 24]
[31 22 36 14 13 38 38 35 11 16]
[14 15 17 34 15 12 15 38 10 17]
[39 15 19 27 28 13 31 14 32 12]


In [74]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [75]:
result = data + ones

print(result)

[2 3]


In [76]:
result = data - ones

print(result)

[0 1]


In [77]:
result = data * data

print(result)

[1 4]


In [78]:
result = data / data

print(result)

[1. 1.]


In [79]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0


In [80]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))

print("Exponent: ", np.exp(arr))

print("Trigonometric Sin: ", np.sin(arr))

print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [81]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [82]:
# Matrix Multiplication
import numpy as np

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


In [83]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Affects Columns

print("Rowwise Sum: ", np.sum(x, axis=1)) # Affects Rows

Array: 
 [1 2 3 4]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [84]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Affects Columns

print("Rowwise Minimum: ", np.min(x, axis=1)) # Affects Rows

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [85]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [86]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


In [87]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

Original Array: 
 [[1 2 3]
 [4 5 6]]


In [88]:
print(x + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [89]:
print(x % 2)

[[1 0 1]
 [0 1 0]]


In [90]:
print(x >= 3)

[[False False  True]
 [ True  True  True]]


In [91]:
print(x % 2 == 0)

[[False  True False]
 [ True False  True]]


In [92]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr)

print('Reversed Array:\n', reversed_arr)


Reversed Array:
 [8 7 6 5 4 3 2 1]


In [93]:
arr = np.array([10, -5, 6, -1])

In [94]:
print("Index of minimum element:", arr.argmin())

Index of minimum element: 1


In [95]:
print("Index of maximum element:", arr.argmax())

Index of maximum element: 0


In [96]:
print("Indexes:", arr.argsort()) # Returns indexes

print("Sorted Array:", arr[ arr.argsort() ])

Indexes: [1 3 2 0]
Sorted Array: [-5 -1  6 10]
